spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    #show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          fetch_size: 200
          order_inserts: true
          order_updates: true
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    table: flyway_history
  application:
    name: rag
  docker:
    compose:
      lifecycle-management: start_only
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: embedded
            platform: postgresql
    openai:
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash
      api-key: ${GEMINI_API_KEY}
      embedding:
        base-url: https://generativelanguage.googleapis.com
        embeddings-path: /v1beta/openai/embeddings
        options:
          model: gemini-embedding-exp-03-07
          #          dimensions: 768 # 1536 is not supported by the text-embedding-004 model
          # https://ai.google.dev/gemini-api/docs/models#gemini-embedding
          #gemini-embedding-exp-03-07 is 1536, but it has a rate limit
    vectorstore:
      pgvector:
        initialize-schema: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
    display-request-duration: true